/// Pedidos de Atacado e E-commerce
table Dim_blingV3_situacoesPedidos
	excludeFromModelRefresh
	lineageTag: c9367ba7-96e9-46ef-9d76-d9180f2c09be

	column id
		dataType: int64
		formatString: 0
		lineageTag: 101d0c4a-fe8f-4b97-813e-04abc4967596
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column cor
		dataType: string
		lineageTag: 16f4a9de-29d4-4a6c-a5b0-8d60d4829ab4
		summarizeBy: none
		sourceColumn: cor

		annotation SummarizationSetBy = Automatic

	column idHerdado
		dataType: int64
		formatString: 0
		lineageTag: 4ca83828-429c-4f0b-b58a-d9c85d13cc14
		summarizeBy: sum
		sourceColumn: idHerdado

		annotation SummarizationSetBy = Automatic

	column modulo
		dataType: string
		lineageTag: 6bbca32f-7bbf-4871-869b-dce0eba43e80
		summarizeBy: none
		sourceColumn: modulo

		annotation SummarizationSetBy = Automatic

	column moduloId
		dataType: int64
		formatString: 0
		lineageTag: 0dfc2692-2972-4640-9fa0-4e2a922f2d5a
		summarizeBy: count
		sourceColumn: moduloId

		annotation SummarizationSetBy = Automatic

	column 'status pedido'
		dataType: string
		lineageTag: 9c9934b7-3ca4-4136-be63-40a608417e00
		summarizeBy: none
		sourceColumn: status pedido

		annotation SummarizationSetBy = Automatic

	column data_atualizacao_warehouse
		dataType: dateTime
		formatString: General Date
		lineageTag: 018c7307-8221-458f-8cdc-a59bb1072f51
		summarizeBy: none
		sourceColumn: data_atualizacao_warehouse

		variation Variation
			isDefault
			relationship: 19c78217-2249-4a4c-be61-78b13e418851
			defaultHierarchy: LocalDateTable_e52266ca-025c-45dc-9787-93cdfef6d2bc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Dim_blingV3_situacoesPedidos = m
		mode: import
		queryGroup: mocks
		source =
				let
				    Fonte = GoogleBigQuery.Database([Implementation="2.0"]),
				    #"coherent-window-444219-c1_Database" = Fonte{[Name="coherent-window-444219-c1",Kind="Database"]}[Data],
				    datalake_Schema = #"coherent-window-444219-c1_Database"{[Name="datalake",Kind="Schema"]}[Data],
				    blingV3_situacoesPedidos_Table = datalake_Schema{[Name="blingV3_situacoesPedidos",Kind="Table"]}[Data],
				    #"Colunas Renomeadas" = Table.RenameColumns(blingV3_situacoesPedidos_Table,{{"nome", "status pedido"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

