table Entradas
	lineageTag: d19925c9-a43e-4745-98d1-37f69a43b8d4

	column Filial
		dataType: int64
		formatString: 0
		lineageTag: 7a8115c2-7929-4887-84bd-c42c2d7a4cfa
		summarizeBy: sum
		sourceColumn: Filial

		annotation SummarizationSetBy = Automatic

	column Prefixo
		dataType: string
		lineageTag: c31e86b1-ffae-4da2-8295-6a778916f80f
		summarizeBy: none
		sourceColumn: Prefixo

		annotation SummarizationSetBy = Automatic

	column 'No. Titulo'
		dataType: string
		lineageTag: 30b45b1f-a6a0-492d-ad1f-85abcb5a8a7c
		summarizeBy: none
		sourceColumn: No. Titulo

		annotation SummarizationSetBy = Automatic

	column Parcela
		dataType: int64
		formatString: 0
		lineageTag: dbb6953f-d2f8-4bef-8294-024bf5ea52a7
		summarizeBy: sum
		sourceColumn: Parcela

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 1af1c7cf-d985-45c7-873c-f9db4c54d413
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: int64
		formatString: 0
		lineageTag: be4e9ecf-b60d-495c-b475-1bab053b8e20
		summarizeBy: sum
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Loja
		dataType: int64
		formatString: 0
		lineageTag: 46ecb019-8834-44c8-8711-33cae2268721
		summarizeBy: sum
		sourceColumn: Loja

		annotation SummarizationSetBy = Automatic

	column 'Nome Cliente'
		dataType: string
		lineageTag: 6d0532dc-87bd-4c6e-8493-0024d63edaf6
		summarizeBy: none
		sourceColumn: Nome Cliente

		annotation SummarizationSetBy = Automatic

	column 'DT Emissao'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4c7c5363-889a-47c6-8441-cff9b3b75486
		summarizeBy: none
		sourceColumn: DT Emissao

		variation Variation
			isDefault
			relationship: ce332a68-8337-4a58-8839-34c518084566
			defaultHierarchy: LocalDateTable_b3977c3d-5fd5-4ca9-a5fe-da54f66f6ef6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Vencto real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 73defe3a-8095-4d35-95ca-23be7c6ff37b
		summarizeBy: none
		sourceColumn: Vencto real

		variation Variation
			isDefault
			relationship: 9a149ccd-e1e0-4168-a6fd-26e251d1e8b4
			defaultHierarchy: LocalDateTable_7c6c2472-4c23-40fe-80ef-d8b51e77d773.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Moeda
		dataType: string
		lineageTag: 2c88c750-371c-4029-9f13-59d531f78187
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column Natureza
		dataType: int64
		formatString: 0
		lineageTag: f01945d4-decb-47f3-9646-18b79cf47e13
		summarizeBy: sum
		sourceColumn: Natureza

		annotation SummarizationSetBy = Automatic

	column 'Taxa moeda'
		dataType: int64
		formatString: 0
		lineageTag: 2b6ffa4e-a925-4a67-a161-a4faebf77f56
		summarizeBy: sum
		sourceColumn: Taxa moeda

		annotation SummarizationSetBy = Automatic

	column 'Vlr.Titulo'
		dataType: double
		lineageTag: 51edab10-3784-4abb-a295-1db52e419fff
		summarizeBy: sum
		sourceColumn: Vlr.Titulo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Saldo Moeda'
		dataType: double
		lineageTag: 11b18791-7942-410d-9408-712d8b4da54b
		summarizeBy: sum
		sourceColumn: Saldo Moeda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Saldo
		dataType: double
		lineageTag: f0549e3d-9f31-4fa0-ae44-127de01c7c73
		summarizeBy: sum
		sourceColumn: Saldo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Saldo a receber'
		dataType: double
		lineageTag: ff5b657d-655f-4a8f-af7e-4c6429a59497
		summarizeBy: sum
		sourceColumn: Saldo a receber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sld.Decresc.'
		dataType: int64
		formatString: 0
		lineageTag: 9ea2a6a0-8eac-4451-a483-717e40649bc9
		summarizeBy: sum
		sourceColumn: Sld.Decresc.

		annotation SummarizationSetBy = Automatic

	column 'Sld.Acresc.'
		dataType: int64
		formatString: 0
		lineageTag: e92c3b82-827d-4309-ac0b-ed44f53f3592
		summarizeBy: sum
		sourceColumn: Sld.Acresc.

		annotation SummarizationSetBy = Automatic

	column Abatimentos
		dataType: int64
		formatString: 0
		lineageTag: a9dd3982-0ed5-4f39-895c-7ac0361bee49
		summarizeBy: sum
		sourceColumn: Abatimentos

		annotation SummarizationSetBy = Automatic

	column 'VL acessorio'
		dataType: int64
		formatString: 0
		lineageTag: 0a2ae16b-7c12-48a4-9cde-58dd68a8b36a
		summarizeBy: sum
		sourceColumn: VL acessorio

		annotation SummarizationSetBy = Automatic

	column Multa
		dataType: int64
		formatString: 0
		lineageTag: 1e148486-bba3-4f27-9438-2b0ec85f38c0
		summarizeBy: sum
		sourceColumn: Multa

		annotation SummarizationSetBy = Automatic

	column Juros
		dataType: int64
		formatString: 0
		lineageTag: e582b092-d4f9-439c-9abd-ca5ef0bb20e5
		summarizeBy: sum
		sourceColumn: Juros

		annotation SummarizationSetBy = Automatic

	column pk = Entradas[No. Titulo] & "_" & Entradas[Parcela]
		lineageTag: af9a0ba7-bee4-43dc-8768-ca92fe822d16
		summarizeBy: count

		annotation SummarizationSetBy = User

	partition Entradas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\rodel\Downloads\Detalhes - 01-03-2026 - 31-03-2026 25-02-2026.xlsx"), null, true),
				    Entradas_Sheet = Fonte{[Item="Entradas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Entradas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Filial", Int64.Type}, {"Prefixo", type text}, {"No. Titulo", type text}, {"Parcela", Int64.Type}, {"Tipo", type text}, {"Cliente", Int64.Type}, {"Loja", Int64.Type}, {"Nome Cliente", type text}, {"DT Emissao", type datetime}, {"Vencto real", type datetime}, {"Moeda", type text}, {"Natureza", Int64.Type}, {"Taxa moeda", Int64.Type}, {"Vlr.Titulo", type number}, {"Saldo Moeda", type number}, {"Saldo", type number}, {"Saldo a receber", type number}, {"Sld.Decresc.", Int64.Type}, {"Sld.Acresc.", Int64.Type}, {"Abatimentos", Int64.Type}, {"VL acessorio", Int64.Type}, {"Multa", Int64.Type}, {"Juros", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Exception

