/// Chamados de SAC e Atendimento ao Cliente
table fato_sac
	lineageTag: 0b6730ba-cf50-4cf2-9955-e97f8e42ba5b

	/// Nota média de atendimento do SAC
	measure 'Nota Média SAC' = AVERAGE(fato_sac[nota_atendimento])
		formatString: 0.0
		lineageTag: a7b96c5f-b933-422a-9269-53773abfccb7

	/// Total de chamados SAC
	measure 'Total Chamados' = COUNTROWS(fato_sac)
		formatString: #,##0
		lineageTag: deaf45f9-c220-4d49-8ed6-d4da432b03e3

	/// Chamados ainda não finalizados
	measure 'Chamados Abertos' = CALCULATE(COUNTROWS(fato_sac), fato_sac[status] IN {"Aberto", "Em Espera"})
		formatString: #,##0
		lineageTag: 306563b9-8181-4d8b-8020-fb0efb8a2678

	/// Chamados já finalizados
	measure 'Chamados Finalizados' = CALCULATE(COUNTROWS(fato_sac), fato_sac[status] = "Finalizado")
		formatString: #,##0
		lineageTag: 8794baa7-5333-43e6-9f09-8f4689a34f7a

	/// Percentual de chamados que cumpriram o SLA
	measure 'Percentual SLA Cumprido' = DIVIDE(CALCULATE(COUNTROWS(fato_sac), fato_sac[sla_cumprido] = TRUE), CALCULATE(COUNTROWS(fato_sac), NOT(ISBLANK(fato_sac[sla_cumprido]))), 0)
		formatString: 0.0%
		lineageTag: 918cac4b-dd43-43b6-81e9-2666a92705e7

	/// Variação da nota média SAC vs período anterior
	measure 'Variacao Nota SAC' =
			VAR Atual = [Nota Média SAC]
			VAR Anterior = CALCULATE([Nota Média SAC], DATEADD(dim_data[Data], -1, MONTH))
			RETURN IF(Anterior <> 0, Atual - Anterior, BLANK())
		formatString: +0.00;-0.00;0.00
		lineageTag: 91296fa9-7a8e-4e9c-a283-bb04c1d686a0

	/// Variação % de chamados abertos vs período anterior
	measure 'Variacao Chamados Abertos %' =
			VAR Atual = [Chamados Abertos]
			VAR Anterior = CALCULATE([Chamados Abertos], DATEADD(dim_data[Data], -1, MONTH))
			RETURN IF(Anterior <> 0, DIVIDE(Atual - Anterior, Anterior), BLANK())
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: 0efb4669-3632-4a3c-9965-cb7e6cb8208d

	/// Variação em pontos percentuais do SLA SAC vs período anterior
	measure 'Variacao SLA SAC %' =
			VAR Atual = [Percentual SLA Cumprido]
			VAR Anterior = CALCULATE([Percentual SLA Cumprido], DATEADD(dim_data[Data], -1, MONTH))
			RETURN IF(Anterior <> 0, Atual - Anterior, BLANK())
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: 8830f58a-18ce-48aa-bd27-76b2d79ec272

	/// Quantidade de chamados com nota 5
	measure 'Notas Nota 5' = CALCULATE(COUNTROWS(fato_sac), fato_sac[nota_atendimento] = 5)
		formatString: 0
		lineageTag: d5e7707f-2237-415a-ade4-7180e5250909

	/// Quantidade de chamados com nota 4
	measure 'Notas Nota 4' = CALCULATE(COUNTROWS(fato_sac), fato_sac[nota_atendimento] = 4)
		formatString: 0
		lineageTag: 97842eab-cbcd-4d01-a53b-fda27b7ef7bc

	/// Quantidade de chamados com nota 3
	measure 'Notas Nota 3' = CALCULATE(COUNTROWS(fato_sac), fato_sac[nota_atendimento] = 3)
		formatString: 0
		lineageTag: 48bc3683-f346-4d2e-9998-1b740ed10f27

	/// Quantidade de chamados com nota 2
	measure 'Notas Nota 2' = CALCULATE(COUNTROWS(fato_sac), fato_sac[nota_atendimento] = 2)
		formatString: 0
		lineageTag: c4e8f737-1406-4ac8-b3dc-a371f3fc93f9

	/// Quantidade de chamados com nota 1
	measure 'Notas Nota 1' = CALCULATE(COUNTROWS(fato_sac), fato_sac[nota_atendimento] = 1)
		formatString: 0
		lineageTag: 97defaae-7bc9-494f-a6bf-3e78991b826c

	/// Net Promoter Score calculado a partir das notas (5=Promotor, 4=Neutro, 1-3=Detrator)
	measure 'NPS Score' =
			VAR TotalAvaliacoes = COUNTROWS(FILTER(fato_sac, fato_sac[nota_atendimento] <> BLANK()))
			VAR Promotores = CALCULATE(COUNTROWS(fato_sac), fato_sac[nota_atendimento] = 5)
			VAR Detratores = CALCULATE(COUNTROWS(fato_sac), fato_sac[nota_atendimento] <= 3)
			RETURN
			IF(
			    TotalAvaliacoes > 0,
			    DIVIDE(Promotores - Detratores, TotalAvaliacoes) * 100,
			    BLANK()
			)
		formatString: 0
		lineageTag: 826b773d-bba4-4e36-bfdc-2dd5ceb287cc

	/// Total de chamados agrupado por categoria (usar no gráfico de rosca)
	measure 'Chamados por Categoria' = COUNTROWS(fato_sac)
		formatString: 0
		lineageTag: 1fd98ce2-59f5-424f-bdcf-b0b80a0c9177

	/// Tempo médio de resolução de chamados em horas
	measure 'Tempo Medio Resolucao' = AVERAGE(fato_sac[tempo_resolucao_horas])
		formatString: 0.0
		lineageTag: 308241e6-16ee-4fcd-a03b-ee11e5e3f9ee

	/// Chamados com status Em Espera
	measure 'Chamados Em Espera' = CALCULATE(COUNTROWS(fato_sac), fato_sac[status] = "Em Espera")
		formatString: 0
		lineageTag: 361a6c2f-3dbc-4632-b2af-3fe812f0df09

	/// Chamados com status Finalizado
	measure 'Chamados Finalizados Total' = CALCULATE(COUNTROWS(fato_sac), fato_sac[status] = "Finalizado")
		formatString: 0
		lineageTag: 13c7ef11-06fb-45b6-b15d-34dbbb141920

	/// Nota média SAC agrupada por mês para gráfico de evolução
	measure 'Nota Media Mensal' = CALCULATE(AVERAGE(fato_sac[nota_atendimento]), ALLEXCEPT(dim_data, dim_data[AnoMes]))
		formatString: 0.0
		lineageTag: f2b66902-fb0d-46c9-99b7-cc9f35f2f719

	/// SLA SAC agrupado por mês para gráfico de evolução
	measure 'SLA Mensal SAC' = CALCULATE([Percentual SLA Cumprido], ALLEXCEPT(dim_data, dim_data[AnoMes]))
		formatString: 0.0%
		lineageTag: 3426a0ed-8aaa-4665-a284-114e95e41b96

	column chamado_id
		dataType: int64
		formatString: 0
		lineageTag: 64b6e5da-5e13-4028-85d8-0caf2705ead5
		summarizeBy: sum
		sourceColumn: chamado_id

		annotation SummarizationSetBy = Automatic

	column cliente_id
		dataType: int64
		formatString: 0
		lineageTag: e2b553d5-f143-470f-9064-50fe6345358a
		summarizeBy: none
		sourceColumn: cliente_id

		annotation SummarizationSetBy = Automatic

	column data_abertura
		dataType: dateTime
		formatString: General Date
		lineageTag: 46c844c7-c73d-4cb7-9ff6-6c55c3a6429e
		summarizeBy: none
		sourceColumn: data_abertura

		variation Variation
			isDefault
			relationship: 1fd91099-35fd-41ce-bb18-f17fe2b87385
			defaultHierarchy: LocalDateTable_5d258021-cfe8-491f-8653-2dec7187d0fa.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_fechamento
		dataType: dateTime
		formatString: General Date
		lineageTag: b7e232bc-de3a-4b2d-acba-33786288d69e
		summarizeBy: none
		sourceColumn: data_fechamento

		variation Variation
			isDefault
			relationship: 1247eb99-f37a-4d80-8b53-afcbc9b17ba8
			defaultHierarchy: LocalDateTable_f886aefa-7298-4190-b87e-8d97277a8f4e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 37c97624-cc33-4b20-b506-4edcb0d7878b
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: b46dbfa3-a96b-4b64-a255-10869a494bbf
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column nota_atendimento
		dataType: int64
		formatString: 0
		lineageTag: 804ffc38-f218-4cb6-b47b-a464c372db29
		summarizeBy: sum
		sourceColumn: nota_atendimento

		annotation SummarizationSetBy = Automatic

	column tempo_resolucao_horas
		dataType: double
		lineageTag: 6bbf08a7-d803-4cd7-a2ac-3543e996e685
		summarizeBy: sum
		sourceColumn: tempo_resolucao_horas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sla_cumprido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4acf8fdc-9399-456c-8ebd-bd024e6785b4
		summarizeBy: none
		sourceColumn: sla_cumprido

		annotation SummarizationSetBy = Automatic

	partition Partition = m
		mode: import
		queryGroup: mocks
		source =
				let
				    Fonte = Table.FromRecords({
				        [chamado_id = 1, cliente_id = 4, data_abertura = #datetime(2025,1,5,9,30,0), data_fechamento = #datetime(2025,1,5,11,45,0), status = "Finalizado", categoria = "Dúvida sobre produto", nota_atendimento = 5, tempo_resolucao_horas = 2.25, sla_cumprido = true],
				        [chamado_id = 2, cliente_id = 5, data_abertura = #datetime(2025,1,6,14,20,0), data_fechamento = #datetime(2025,1,6,16,10,0), status = "Finalizado", categoria = "Rastreamento", nota_atendimento = 4, tempo_resolucao_horas = 1.83, sla_cumprido = true],
				        [chamado_id = 3, cliente_id = 8, data_abertura = #datetime(2025,1,7,10,15,0), data_fechamento = null, status = "Aberto", categoria = "Reclamação", nota_atendimento = null, tempo_resolucao_horas = null, sla_cumprido = null],
				        [chamado_id = 4, cliente_id = 10, data_abertura = #datetime(2025,1,7,11,0,0), data_fechamento = #datetime(2025,1,8,9,30,0), status = "Finalizado", categoria = "Troca de produto", nota_atendimento = 3, tempo_resolucao_horas = 22.50, sla_cumprido = false],
				        [chamado_id = 5, cliente_id = 4, data_abertura = #datetime(2025,1,8,15,45,0), data_fechamento = #datetime(2025,1,8,16,30,0), status = "Finalizado", categoria = "Dúvida sobre frete", nota_atendimento = 5, tempo_resolucao_horas = 0.75, sla_cumprido = true],
				        [chamado_id = 6, cliente_id = 6, data_abertura = #datetime(2025,1,9,8,0,0), data_fechamento = null, status = "Em Espera", categoria = "Cancelamento", nota_atendimento = null, tempo_resolucao_horas = null, sla_cumprido = null],
				        [chamado_id = 7, cliente_id = 5, data_abertura = #datetime(2025,1,9,13,20,0), data_fechamento = #datetime(2025,1,9,14,45,0), status = "Finalizado", categoria = "Elogio", nota_atendimento = 5, tempo_resolucao_horas = 1.42, sla_cumprido = true],
				        [chamado_id = 8, cliente_id = 8, data_abertura = #datetime(2025,1,10,9,10,0), data_fechamento = null, status = "Aberto", categoria = "Problema com pagamento", nota_atendimento = null, tempo_resolucao_horas = null, sla_cumprido = null],
				        [chamado_id = 9, cliente_id = 1, data_abertura = #datetime(2025,1,8,16,30,0), data_fechamento = #datetime(2025,1,9,10,15,0), status = "Finalizado", categoria = "Informação comercial", nota_atendimento = 4, tempo_resolucao_horas = 17.75, sla_cumprido = false],
				        [chamado_id = 10, cliente_id = 2, data_abertura = #datetime(2025,1,9,11,50,0), data_fechamento = #datetime(2025,1,9,13,20,0), status = "Finalizado", categoria = "Dúvida sobre prazo", nota_atendimento = 4, tempo_resolucao_horas = 1.50, sla_cumprido = true]
				    }),
				    TiposDefinidos = Table.TransformColumnTypes(Fonte,{
				        {"chamado_id", Int64.Type},
				        {"cliente_id", Int64.Type},
				        {"data_abertura", type datetime},
				        {"data_fechamento", type datetime},
				        {"status", type text},
				        {"categoria", type text},
				        {"nota_atendimento", Int64.Type},
				        {"tempo_resolucao_horas", type number},
				        {"sla_cumprido", type logical}
				    })
				in
				    TiposDefinidos

	annotation PBI_ResultType = Table

