table 'fato _blingV3_notasFiscais'
	lineageTag: 64721435-8b5a-4c50-bc9d-19df0e283d34

	measure Faturamento =
			FORMAT(
			SUM('fato _blingV3_notasFiscais'[valorNota]),
			    "R$ #,##0.00"
			)
		lineageTag: a9501b71-b951-41d0-8e8c-e144b6173fe2

	measure 'Custo Total Frete Formatado' = ```
			
			FORMAT(
			    SUM('fato _blingV3_notasFiscais'[valorFrete]),
			    "R$ #,##0.00"
			) 
			```
		lineageTag: 40df52eb-95f1-4896-96c7-a372cb58742e

	column id
		dataType: int64
		formatString: 0
		lineageTag: 3d07e969-5763-47bb-a1e6-9b7b8054cc8c
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column tipo
		dataType: int64
		formatString: 0
		lineageTag: 13467121-9fcf-46c5-9f50-fefbf6e7c521
		summarizeBy: sum
		sourceColumn: tipo

		annotation SummarizationSetBy = Automatic

	column situacao
		dataType: int64
		formatString: 0
		lineageTag: 4d6660ee-70f8-42c9-aa10-3e825d99e358
		summarizeBy: none
		sourceColumn: situacao

		annotation SummarizationSetBy = Automatic

	column numero
		dataType: int64
		formatString: 0
		lineageTag: 2c58d096-a961-4dbf-98c4-a4f22de4e244
		summarizeBy: sum
		sourceColumn: numero

		annotation SummarizationSetBy = Automatic

	column serie
		dataType: int64
		formatString: 0
		lineageTag: bc0fa3b7-33a1-42eb-bc67-9ba6f3aff363
		summarizeBy: sum
		sourceColumn: serie

		annotation SummarizationSetBy = Automatic

	column dataEmissao
		dataType: dateTime
		formatString: Short Date
		lineageTag: b7b79e75-0e6d-4a2b-a6ed-626823517c90
		summarizeBy: none
		sourceColumn: dataEmissao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column valorNota
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 6fde659f-c5ed-4fa6-a5c1-fc5fe0c95945
		summarizeBy: sum
		sourceColumn: valorNota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column valorFrete
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 43ea5144-0cea-4fa7-b944-cd006798a9e4
		summarizeBy: sum
		sourceColumn: valorFrete

		annotation SummarizationSetBy = Automatic

	column optanteSimplesNacional
		dataType: string
		lineageTag: abeb042e-67ce-4701-bc8f-82a549fd29a2
		summarizeBy: none
		sourceColumn: optanteSimplesNacional

		annotation SummarizationSetBy = Automatic

	column numeroPedidoLoja
		dataType: string
		lineageTag: 4102f6a6-0484-45db-8fda-532ac18d8ee0
		summarizeBy: none
		sourceColumn: numeroPedidoLoja

		annotation SummarizationSetBy = Automatic

	column naturezaOperacao
		dataType: string
		lineageTag: 2f4122fd-435d-42d2-9da7-7c6bf7458e3d
		summarizeBy: none
		sourceColumn: naturezaOperacao

		annotation SummarizationSetBy = Automatic

	column loja
		dataType: string
		lineageTag: e2c1e566-9178-4748-828a-6c1f0d2529e4
		summarizeBy: none
		sourceColumn: loja

		annotation SummarizationSetBy = Automatic

	column vendedor
		dataType: string
		lineageTag: 14745168-00e0-474a-a037-892273dc06b1
		summarizeBy: none
		sourceColumn: vendedor

		annotation SummarizationSetBy = Automatic

	column parcelas
		dataType: string
		lineageTag: 4026cefa-eca4-426b-96ae-10a1c14e893e
		summarizeBy: none
		sourceColumn: parcelas

		annotation SummarizationSetBy = Automatic

	column data_atualizacao_warehouse
		dataType: dateTime
		formatString: General Date
		lineageTag: 57998cbc-bbfc-4c00-920f-2a134a5973e2
		summarizeBy: none
		sourceColumn: data_atualizacao_warehouse

		variation Variation
			isDefault
			relationship: dc6377b2-febe-4b9b-9729-02041502aea1
			defaultHierarchy: LocalDateTable_c38dee5d-2ba7-4323-a945-0cd9b106333b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Tipo Venda' =
			
			VAR PedidoNota = 'fato _blingV3_notasFiscais'[id]
			
			RETURN
			IF(
			    PedidoNota IN VALUES(fato_blingV3Atacado_pedidosVendas[id]),
			    "Atacado",
			    "Venda"
			)
		lineageTag: 6eccce15-4b27-4528-bcc9-d3d02d3ae253
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'fato _blingV3_notasFiscais' = m
		mode: import
		queryGroup: mocks
		source =
				let
				    Fonte = GoogleBigQuery.Database([Implementation="2.0"]),
				    Projeto = Fonte{[Name="coherent-window-444219-c1", Kind="Database"]}[Data],
				    Schema = Projeto{[Name="datalake", Kind="Schema"]}[Data],
				    NotasFiscais = Schema{[Name="blingV3_notasFiscais", Kind="Table"]}[Data],
				
				    Tipos =
				        Table.TransformColumnTypes(
				            NotasFiscais,
				            {
				                {"numero", Int64.Type},
				                {"valorNota", Currency.Type},
				                {"valorFrete", Currency.Type},
				                {"dataEmissao", type datetime},
				                {"dataOperacao", type datetime}
				            }
				        ),
				
				    Datas =
				        Table.TransformColumnTypes(
				            Tipos,
				            {
				                {"dataEmissao", type date}
				            },
				            "pt-BR"
				        ),
				    #"Colunas Removidas" = Table.RemoveColumns(Datas,{"xml", "linkDanfe", "linkPDF", "contato", "transporte", "itens", "dataOperacao", "chaveAcesso"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"id", Int64.Type}, {"tipo", Int64.Type}, {"situacao", Int64.Type}, {"serie", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

