table medidas_financeiro
	lineageTag: 931ad143-9708-4495-ba4d-484963756635

	/// Soma do saldo de todos os títulos em aberto (saldo > 0)
	measure 'CR Total a Receber' = ```
			
			VAR DataFinal =
			    MAX ( calendario[Date] )
			RETURN   
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
			```
		formatString: R$ #,##0.00
		displayFolder: Recebimentos
		lineageTag: 10de0ace-94cb-4c7b-8a31-d7bcec1448b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Valor total recebido (títulos baixados), incluindo juros e multa
	measure 'CR Recebido no Período' =
			
			CALCULATE(
			    SUMX(
			        protheus_contasReceber,
			        protheus_contasReceber[valor_titulo] +
			        protheus_contasReceber[valor_juros] +
			        protheus_contasReceber[valor_multa]
			    ),
			    NOT(ISBLANK(protheus_contasReceber[data_baixa]))
			)
		formatString: R$ #,##0.00
		displayFolder: Recebimentos
		lineageTag: 26c03b56-2cf3-42a1-8ed8-4e7f42e0bac6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Percentual de inadimplência: valor vencido / total em aberto
	measure 'CR Inadimplência %' =
			
			DIVIDE(
			    [CR Valor Inadimplente],
			    [CR Total]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Inadimplência
		lineageTag: a4eeb8c2-e6db-4b2f-96fc-5241adb8a566

	/// Prazo Médio de Recebimento em dias, ponderado pelo valor do título. Exclui outliers acima de 180 dias ou antecipações acima de 60 dias.
	measure 'CR PMR (dias)' =
			
			DIVIDE(
			    SUMX(
			        FILTER(
			            protheus_contasReceber,
			            NOT(ISBLANK(protheus_contasReceber[data_baixa])) &&
			            DATEDIFF(
			                protheus_contasReceber[data_vencimento],
			                protheus_contasReceber[data_baixa],
			                DAY
			            ) >= -60 &&
			            DATEDIFF(
			                protheus_contasReceber[data_vencimento],
			                protheus_contasReceber[data_baixa],
			                DAY
			            ) <= 180
			        ),
			        DATEDIFF(
			            protheus_contasReceber[data_vencimento],
			            protheus_contasReceber[data_baixa],
			            DAY
			        ) * protheus_contasReceber[valor_titulo]
			    ),
			    CALCULATE(
			        SUM(protheus_contasReceber[valor_titulo]),
			        NOT(ISBLANK(protheus_contasReceber[data_baixa]))
			    )
			)
		formatString: 0.0 " dias"
		displayFolder: PMR
		lineageTag: 61b03866-4a60-4303-b412-a54f43b63a1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Valor base para análise de aging (curva de vencimentos). Usar com faixas de dias para estratificar o portfólio.
	measure 'CR Valor Aging' =
			
			VAR DataFinal =
			    MAX ( calendario[Date] )
			
			RETURN
			CALCULATE(
			    SUM ( protheus_contasReceber[saldo] ),
			    protheus_contasReceber[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: Aging
		lineageTag: 2bc60ee4-fc28-4225-aecb-57218f467b29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Valor em aberto por cliente, usado na tabela de detalhamento de inadimplência
	measure 'CR Valor em Aberto por Cliente' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: Status Cliente
		lineageTag: fcb96510-1d6d-44f7-a096-d61ccb4a8562

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Quantidade de dias em atraso do título mais antigo do cliente no contexto atual
	measure 'CR Dias em Atraso' =
			
			VAR dias =
			    DATEDIFF(
			        MIN(protheus_contasReceber[data_vencimento]),
			        TODAY(),
			        DAY
			    )
			RETURN
			IF(dias > 0, dias, 0)
		formatString: 0
		displayFolder: Status Cliente
		lineageTag: cf00e4e9-ef1a-4e05-82b7-a8de313b0ae9

	/// Classificação do cliente por situação de atraso: Em Dia / Atraso Leve (até 30d) / Moderado (até 90d) / Grave (90d+)
	measure 'CR Status do Cliente' =
			
			SWITCH(
			    TRUE(),
			    [CR Dias em Atraso] = 0, "Em Dia",
			    [CR Dias em Atraso] <= 30, "Atraso Leve",
			    [CR Dias em Atraso] <= 90, "Atraso Moderado",
			    "Atraso Grave"
			)
		displayFolder: Status Cliente
		lineageTag: f54af439-07bc-4bb2-94ed-ff45a10b2ab5

	/// Saldo total de obrigações em aberto (Contas a Pagar)
	measure 'CP Total a Pagar' =
			CALCULATE(
			    SUM(protheus_contasPagar[saldo]),
			    protheus_contasPagar[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: CP Pagamentos
		lineageTag: 03f4100c-86ab-4379-9576-9401408385a7

	/// Valor total pago (títulos baixados), incluindo juros e multa
	measure 'CP Pagamentos Realizados no Período' =
			CALCULATE(
			    SUMX(
			        protheus_contasPagar,
			        protheus_contasPagar[valor_titulo] +
			        protheus_contasPagar[valor_juros] +
			        protheus_contasPagar[valor_multa]
			    ),
			    NOT(ISBLANK(protheus_contasPagar[data_baixa]))
			)
		formatString: R$ #,##0.00
		displayFolder: CP Pagamentos
		lineageTag: eb786ca9-3f74-4f99-92d4-cd244398a1de

	/// Saldo de títulos vencidos e ainda não pagos
	measure 'CP Valor em Atraso' =
			CALCULATE(
			    SUM(protheus_contasPagar[saldo]),
			    protheus_contasPagar[saldo] > 0,
			    protheus_contasPagar[data_vencimento] < TODAY()
			)
		formatString: R$ #,##0.00
		displayFolder: CP Atraso
		lineageTag: 88b93010-f077-48ea-b31b-06b876c8f26f

	/// Quantidade de títulos vencidos e não pagos
	measure 'CP Qtd Títulos em Atraso' =
			CALCULATE(
			    COUNTROWS(protheus_contasPagar),
			    protheus_contasPagar[saldo] > 0,
			    protheus_contasPagar[data_vencimento] < TODAY()
			)
		formatString: 0
		displayFolder: CP Atraso
		lineageTag: 320501e6-04d4-43ff-a83e-a2f6d02c4888

	/// Prazo Médio de Pagamento em dias, ponderado pelo valor do título
	measure 'CP PMP (dias)' =
			DIVIDE(
			    SUMX(
			        FILTER(
			            protheus_contasPagar,
			            NOT(ISBLANK(protheus_contasPagar[data_baixa])) &&
			            DATEDIFF(
			                protheus_contasPagar[data_emissao],
			                protheus_contasPagar[data_baixa],
			                DAY
			            ) >= 0 &&
			            DATEDIFF(
			                protheus_contasPagar[data_emissao],
			                protheus_contasPagar[data_baixa],
			                DAY
			            ) <= 365
			        ),
			        DATEDIFF(
			            protheus_contasPagar[data_emissao],
			            protheus_contasPagar[data_baixa],
			            DAY
			        ) * protheus_contasPagar[valor_titulo]
			    ),
			    CALCULATE(
			        SUM(protheus_contasPagar[valor_titulo]),
			        NOT(ISBLANK(protheus_contasPagar[data_baixa]))
			    )
			)
		formatString: 0.0 " dias"
		displayFolder: CP PMP
		lineageTag: e4e242ca-6701-49f2-be78-0a00b65b53fc

	/// Saldo em aberto para análise de aging (usar com faixa_aging)
	measure 'CP Valor Aging' =
			CALCULATE(
			    SUM(protheus_contasPagar[saldo]),
			    protheus_contasPagar[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: CP Aging
		lineageTag: 95966676-729d-427a-91ab-b24d889256d8

	measure 'Total Entrada' =
			
			CALCULATE(
			    SUM(protheus_movimentosBancarios[valor]),
			    protheus_movimentosBancarios[receb_pagto] = "R"
			)
		displayFolder: Caixa
		lineageTag: 640c1a1e-f1fa-4158-9481-b23ca010254c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Saída' =
			
			-1 * CALCULATE(
			    SUM(protheus_movimentosBancarios[valor]),
			    protheus_movimentosBancarios[receb_pagto] = "P"
			)
		displayFolder: Caixa
		lineageTag: 10128ec6-e5fa-469b-8cdb-8d5305a4b6ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Saldo Projetado (depois)' =
			
			VAR SaldoInicial = SUM ( protheus_contasBancarias[saldo_atual] )
			VAR DataEixo     = MAX ( calendario[Date] )
			VAR DataInicio   = MINX ( ALLSELECTED ( calendario[Date] ), calendario[Date] )
			
			VAR TemMovNoDia =
			    CALCULATE (
			        COUNTROWS ( projecao_caixa ),
			        USERELATIONSHIP ( calendario[Date], projecao_caixa[data_vencimento_ajustada] ),
			        KEEPFILTERS ( calendario[Date] = DataEixo )
			    )
			
			VAR AcumAteDia =
			    CALCULATE (
			        SUM ( projecao_caixa[valorpn] ),
			        USERELATIONSHIP ( calendario[Date], projecao_caixa[data_vencimento_ajustada] ),
			        FILTER (
			            ALL ( calendario[Date] ),
			            calendario[Date] >= DataInicio
			                && calendario[Date] <= DataEixo
			        )
			    )
			
			RETURN
			    IF ( TemMovNoDia = 0, BLANK(), SaldoInicial + AcumAteDia )
		displayFolder: Caixa
		lineageTag: 41637e26-7271-49b6-abb8-861781c86cb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Saldo Realizado (antes)' =
			
			VAR SaldoFuturo =
			    SUM ( protheus_contasBancarias[saldo_atual] )
			VAR DataEixo =
			    MAX ( calendario[Date] )
			VAR TemMovNoDia =
			    CALCULATE (
			        COUNTROWS ( protheus_movimentosBancarios ),
			        KEEPFILTERS ( protheus_movimentosBancarios[data_movimento] = DataEixo )
			    )
			VAR SomaAPartirDoDia =
			    CALCULATE (
			        SUM ( protheus_movimentosBancarios[valorpn] ),
			        FILTER ( ALL ( calendario[Date] ), calendario[Date] >= DataEixo )
			    )
			RETURN
			    IF ( TemMovNoDia = 0, BLANK(), SaldoFuturo - SomaAPartirDoDia )
		displayFolder: Caixa
		lineageTag: 6169de71-d0f7-455b-bf17-4dab9d9c47a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CP Dias em Atraso' =
			
			VAR dataMin =
			    CALCULATE(
			        MIN(protheus_contasPagar[data_vencimento]),
			        protheus_contasPagar[status_pagamento] = "Atrasado"
			    )
			VAR dias =
			    IF(
			        NOT ISBLANK(dataMin),
			        DATEDIFF(dataMin, TODAY(), DAY)
			    )
			RETURN
			IF(dias > 0, dias, 0)
		formatString: 0
		displayFolder: Status Cliente
		lineageTag: 21a4fb22-be77-4c71-be1c-30b8d73b2aa9

	measure 'CP Status do Fornecedor' =
			
			SWITCH(
			    TRUE(),
			    [CP Dias em Atraso] = 0, "Em Dia",
			    [CP Dias em Atraso] <= 30, "Atraso Leve",
			    [CP Dias em Atraso] <= 90, "Atraso Moderado",
			    "Atraso Grave"
			)
		displayFolder: Status Cliente
		lineageTag: b20f7d9c-95cd-42c4-aee0-d3bf7ceceb3a

	measure 'CP Valor em Aberto por Fornecedor' =
			
			CALCULATE(
			    SUM(protheus_contasPagar[saldo]),
			    protheus_contasPagar[saldo] > 0
			)
		displayFolder: Status Cliente
		lineageTag: 7410346b-ad8f-4c46-a199-42dd9a5b571a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultado Operacional' = SUM(protheus_movimentosBancarios[valorpn])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Caixa
		lineageTag: fa530358-f3a5-4759-bf96-0f4d91225de6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Acumulado Projetado' =
			
			[Saldo Inicial Periodo] + [Fluxo Acumulado Projetado]
		displayFolder: Caixa
		lineageTag: c944d689-7a17-4f61-89ec-9d0c495e6b44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fluxo Liquido Projetado' = SUM(protheus_contasReceber[valor_titulo]) - SUM(protheus_contasPagar[valor_titulo])
		formatString: "R$"#,0.00;-"R$"#,0.00;"R$"#,0.00
		displayFolder: Caixa
		lineageTag: ba2cfaf8-6f57-40d8-8515-02a5d6a0e19b

		annotation PBI_FormatHint = {"currencyCulture":"es-BR"}

	measure 'Fluxo Liquido Real' = SUM(protheus_movimentosBancarios[valorpn])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Caixa
		lineageTag: d2ef96c9-98d7-4c02-8a71-9da19805277d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Acumulado Real' =
			
			[Saldo Inicial Periodo] + [Fluxo Acumulado Real]
		displayFolder: Caixa
		lineageTag: a15fb5e6-a015-4b78-8cbe-7cca3a25498b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Saldo de títulos vencidos e ainda não pagos (data_vencimento < hoje)
	measure 'CR Valor Inadimplente' =
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0,
			    protheus_contasReceber[data_vencimento] < TODAY()
			)
		formatString: R$ #,##0.00
		displayFolder: Inadimplência
		lineageTag: 3622134b-ecf7-4f08-8012-27fa3f21755b

	/// Total de saldo em aberto no período selecionado
	measure 'CR Total' = SUM(protheus_contasReceber[valor_titulo])
		formatString: R$ #,##0.00
		displayFolder: Recebimentos
		lineageTag: 084fe15d-3059-449a-a67a-8a935933c0ab

	measure 'Saldo Inicial Periodo' =
			VAR DataInicial =
			    MIN('calendario'[Date])
			
			RETURN
			CALCULATE(
			    [Fluxo Liquido Projetado],
			    FILTER(
			        ALL('Calendario'),
			        'Calendario'[Date] < DataInicial
			    )
			)
		displayFolder: Caixa
		lineageTag: 8919a334-c86c-4395-9a0f-678cc69ead14

	measure 'Fluxo Acumulado Projetado' =
			CALCULATE(
			    [Fluxo Liquido Projetado],
			    FILTER(
			        ALLSELECTED('Calendario'[Date]),
			        'Calendario'[Date] <= MAX('Calendario'[Date])
			    )
			)
		displayFolder: Caixa
		lineageTag: b1796501-2579-4f96-b758-cec5bc534901

	measure 'Fluxo Acumulado Real' =
			CALCULATE(
			    [Fluxo Liquido Real],
			    FILTER(
			        ALLSELECTED('Calendario'[Date]),
			        'Calendario'[Date] <= MAX('Calendario'[Date])
			    )
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Caixa
		lineageTag: 8209dc6e-9084-4b2d-86d7-ea9dd51b6613

	partition medidas_financeiro = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

