table medidas_financeiro
	lineageTag: 931ad143-9708-4495-ba4d-484963756635

	/// Soma do saldo de todos os títulos em aberto (saldo > 0)
	measure 'CR Total a Receber' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: Recebimentos
		lineageTag: 10de0ace-94cb-4c7b-8a31-d7bcec1448b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Valor total recebido (títulos baixados), incluindo juros e multa
	measure 'CR Recebido no Período' =
			
			CALCULATE(
			    SUMX(
			        protheus_contasReceber,
			        protheus_contasReceber[valor_titulo] +
			        protheus_contasReceber[valor_juros] +
			        protheus_contasReceber[valor_multa]
			    ),
			    NOT(ISBLANK(protheus_contasReceber[data_baixa]))
			)
		formatString: R$ #,##0.00
		displayFolder: Recebimentos
		lineageTag: 26c03b56-2cf3-42a1-8ed8-4e7f42e0bac6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Saldo de títulos vencidos e ainda não pagos (data_vencimento < hoje)
	measure 'CR Valor Inadimplente' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0,
			    protheus_contasReceber[data_vencimento] < TODAY()
			)
		formatString: R$ #,##0.00
		displayFolder: Inadimplência
		lineageTag: ed756031-7a46-4f13-8cee-82c1c4744557

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total de saldo em aberto no período selecionado
	measure 'CR Total em Aberto' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: Recebimentos
		lineageTag: c13ef7e8-fac8-47fe-a6a5-401e2756e597

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Percentual de inadimplência: valor vencido / total em aberto
	measure 'CR Inadimplência %' =
			
			DIVIDE(
			    [CR Valor Inadimplente],
			    [CR Total em Aberto]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Inadimplência
		lineageTag: a4eeb8c2-e6db-4b2f-96fc-5241adb8a566

	/// Prazo Médio de Recebimento em dias, ponderado pelo valor do título. Exclui outliers acima de 180 dias ou antecipações acima de 60 dias.
	measure 'CR PMR (dias)' =
			
			DIVIDE(
			    SUMX(
			        FILTER(
			            protheus_contasReceber,
			            NOT(ISBLANK(protheus_contasReceber[data_baixa])) &&
			            DATEDIFF(
			                protheus_contasReceber[data_vencimento],
			                protheus_contasReceber[data_baixa],
			                DAY
			            ) >= -60 &&
			            DATEDIFF(
			                protheus_contasReceber[data_vencimento],
			                protheus_contasReceber[data_baixa],
			                DAY
			            ) <= 180
			        ),
			        DATEDIFF(
			            protheus_contasReceber[data_vencimento],
			            protheus_contasReceber[data_baixa],
			            DAY
			        ) * protheus_contasReceber[valor_titulo]
			    ),
			    CALCULATE(
			        SUM(protheus_contasReceber[valor_titulo]),
			        NOT(ISBLANK(protheus_contasReceber[data_baixa]))
			    )
			)
		formatString: 0.0 " dias"
		displayFolder: PMR
		lineageTag: 61b03866-4a60-4303-b412-a54f43b63a1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// PMR do mês anterior ao período selecionado, para cálculo de variação
	measure 'CR PMR Período Anterior' =
			
			CALCULATE(
			    [CR PMR (dias)],
			    DATEADD(calendario[Date], -1, MONTH)
			)
		formatString: 0.0 " dias"
		displayFolder: PMR
		lineageTag: 5936107d-ab0b-41c0-b444-8f22ac477652

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Variação em dias do PMR vs período anterior. Positivo = piorou; negativo = melhorou.
	measure 'CR Variação PMR' =
			
			[CR PMR (dias)] - [CR PMR Período Anterior]
		formatString: 0.0 " dias"
		displayFolder: PMR
		lineageTag: dc03d6da-4489-4930-ad85-f164872ac32f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Valor base para análise de aging (curva de vencimentos). Usar com faixas de dias para estratificar o portfólio.
	measure 'CR Valor Aging' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: Aging
		lineageTag: 2bc60ee4-fc28-4225-aecb-57218f467b29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Valor inadimplente calculado até a data máxima do período selecionado no calendário
	measure 'CR Valor Inadimplente (Posição)' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    FILTER(
			        ALL(protheus_contasReceber),
			        protheus_contasReceber[data_emissao] <= MAX(calendario[Date]) &&
			        (
			            ISBLANK(protheus_contasReceber[data_baixa]) ||
			            protheus_contasReceber[data_baixa] > MAX(calendario[Date])
			        ) &&
			        protheus_contasReceber[data_vencimento] < MAX(calendario[Date])
			    )
			)
		formatString: R$ #,##0.00
		displayFolder: Inadimplência
		lineageTag: aaa2e6d8-f943-4301-8924-dd7904b156b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total em aberto calculado até a data máxima do período selecionado no calendário
	measure 'CR Total em Aberto (Posição)' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    FILTER(
			        ALL(protheus_contasReceber),
			        protheus_contasReceber[data_emissao] <= MAX(calendario[Date]) &&
			        (
			            ISBLANK(protheus_contasReceber[data_baixa]) ||
			            protheus_contasReceber[data_baixa] > MAX(calendario[Date])
			        )
			    )
			)
		formatString: R$ #,##0.00
		displayFolder: Inadimplência
		lineageTag: b30ec5c9-792c-4dfd-9891-2b4d20e61943

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Percentual de inadimplência calculado sobre a posição do período selecionado no calendário
	measure 'CR Inadimplência % (Posição)' =
			
			VAR total_mes =
			    [CR Total em Aberto (Posição)]
			RETURN
			IF(
			    total_mes > 0,
			    DIVIDE(
			        [CR Valor Inadimplente (Posição)],
			        total_mes
			    ),
			    BLANK()
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Inadimplência
		lineageTag: 92b7a087-e8f7-4090-ae7c-4f9a520faba4

	/// Valor em aberto por cliente, usado na tabela de detalhamento de inadimplência
	measure 'CR Valor em Aberto por Cliente' =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: Status Cliente
		lineageTag: fcb96510-1d6d-44f7-a096-d61ccb4a8562

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Quantidade de dias em atraso do título mais antigo do cliente no contexto atual
	measure 'CR Dias em Atraso' =
			
			VAR dias =
			    DATEDIFF(
			        MIN(protheus_contasReceber[data_vencimento]),
			        TODAY(),
			        DAY
			    )
			RETURN
			IF(dias > 0, dias, 0)
		formatString: 0
		displayFolder: Status Cliente
		lineageTag: cf00e4e9-ef1a-4e05-82b7-a8de313b0ae9

	/// Classificação do cliente por situação de atraso: Em Dia / Atraso Leve (até 30d) / Moderado (até 90d) / Grave (90d+)
	measure 'CR Status do Cliente' =
			
			SWITCH(
			    TRUE(),
			    [CR Dias em Atraso] = 0, "Em Dia",
			    [CR Dias em Atraso] <= 30, "Atraso Leve",
			    [CR Dias em Atraso] <= 90, "Atraso Moderado",
			    "Atraso Grave"
			)
		displayFolder: Status Cliente
		lineageTag: f54af439-07bc-4bb2-94ed-ff45a10b2ab5

	/// Saldo total de obrigações em aberto (Contas a Pagar)
	measure 'CP Total a Pagar' =
			CALCULATE(
			    SUM(protheus_contasPagar[saldo]),
			    protheus_contasPagar[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: CP Pagamentos

	/// Valor total pago (títulos baixados), incluindo juros e multa
	measure 'CP Pagamentos Realizados no Período' =
			CALCULATE(
			    SUMX(
			        protheus_contasPagar,
			        protheus_contasPagar[valor_titulo] +
			        protheus_contasPagar[valor_juros] +
			        protheus_contasPagar[valor_multa]
			    ),
			    NOT(ISBLANK(protheus_contasPagar[data_baixa]))
			)
		formatString: R$ #,##0.00
		displayFolder: CP Pagamentos

	/// Saldo de títulos vencidos e ainda não pagos
	measure 'CP Valor em Atraso' =
			CALCULATE(
			    SUM(protheus_contasPagar[saldo]),
			    protheus_contasPagar[saldo] > 0,
			    protheus_contasPagar[data_vencimento] < TODAY()
			)
		formatString: R$ #,##0.00
		displayFolder: CP Atraso

	/// Quantidade de títulos vencidos e não pagos
	measure 'CP Qtd Títulos em Atraso' =
			CALCULATE(
			    COUNTROWS(protheus_contasPagar),
			    protheus_contasPagar[saldo] > 0,
			    protheus_contasPagar[data_vencimento] < TODAY()
			)
		formatString: 0
		displayFolder: CP Atraso

	/// Prazo Médio de Pagamento em dias, ponderado pelo valor do título
	measure 'CP PMP (dias)' =
			DIVIDE(
			    SUMX(
			        FILTER(
			            protheus_contasPagar,
			            NOT(ISBLANK(protheus_contasPagar[data_baixa])) &&
			            DATEDIFF(
			                protheus_contasPagar[data_emissao],
			                protheus_contasPagar[data_baixa],
			                DAY
			            ) >= 0 &&
			            DATEDIFF(
			                protheus_contasPagar[data_emissao],
			                protheus_contasPagar[data_baixa],
			                DAY
			            ) <= 365
			        ),
			        DATEDIFF(
			            protheus_contasPagar[data_emissao],
			            protheus_contasPagar[data_baixa],
			            DAY
			        ) * protheus_contasPagar[valor_titulo]
			    ),
			    CALCULATE(
			        SUM(protheus_contasPagar[valor_titulo]),
			        NOT(ISBLANK(protheus_contasPagar[data_baixa]))
			    )
			)
		formatString: 0.0 " dias"
		displayFolder: CP PMP

	/// Valor total programado a pagar (títulos em aberto, pelo valor original)
	measure 'CP Total Programado' =
			CALCULATE(
			    SUM(protheus_contasPagar[valor_titulo]),
			    protheus_contasPagar[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: CP Pagamentos

	/// Saldo em aberto para análise de aging (usar com faixa_aging)
	measure 'CP Valor Aging' =
			CALCULATE(
			    SUM(protheus_contasPagar[saldo]),
			    protheus_contasPagar[saldo] > 0
			)
		formatString: R$ #,##0.00
		displayFolder: CP Aging

	partition medidas_financeiro = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

