table medidas_financeiro
	lineageTag: 931ad143-9708-4495-ba4d-484963756635

	measure 01_total_a_receber =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		lineageTag: 10de0ace-94cb-4c7b-8a31-d7bcec1448b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 02_recebido_no_periodo =
			
			CALCULATE(
			    SUMX(
			        protheus_contasReceber,
			        protheus_contasReceber[valor_titulo] +
			        protheus_contasReceber[valor_juros] +
			        protheus_contasReceber[valor_multa]
			    ),
			    NOT(ISBLANK(protheus_contasReceber[data_baixa]))
			)
		lineageTag: 26c03b56-2cf3-42a1-8ed8-4e7f42e0bac6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 03_valor_inadimplente =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0,
			    protheus_contasReceber[data_vencimento] < TODAY()
			)
		lineageTag: ed756031-7a46-4f13-8cee-82c1c4744557

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 04_total_aberto =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		lineageTag: c13ef7e8-fac8-47fe-a6a5-401e2756e597

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 05_inadimplencia_percentual =
			
			DIVIDE(
			    [03_valor_inadimplente],
			    [04_total_aberto]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a4eeb8c2-e6db-4b2f-96fc-5241adb8a566

	measure 06_pmr_dias =
			
			DIVIDE(
			    SUMX(
			        FILTER(
			            protheus_contasReceber,
			            NOT(ISBLANK(protheus_contasReceber[data_baixa])) &&
			            DATEDIFF(
			                protheus_contasReceber[data_vencimento],
			                protheus_contasReceber[data_baixa],
			                DAY
			            ) >= -60 &&
			            DATEDIFF(
			                protheus_contasReceber[data_vencimento],
			                protheus_contasReceber[data_baixa],
			                DAY
			            ) <= 180
			        ),
			        DATEDIFF(
			            protheus_contasReceber[data_vencimento],
			            protheus_contasReceber[data_baixa],
			            DAY
			        ) * protheus_contasReceber[valor_titulo]
			    ),
			    CALCULATE(
			        SUM(protheus_contasReceber[valor_titulo]),
			        NOT(ISBLANK(protheus_contasReceber[data_baixa]))
			    )
			)
		lineageTag: 61b03866-4a60-4303-b412-a54f43b63a1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 07_pmr_periodo_anterior =
			
			CALCULATE(
			    [06_pmr_dias],
			    DATEADD(calendario[Date], -1, MONTH)
			)
		lineageTag: 5936107d-ab0b-41c0-b444-8f22ac477652

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 08_variacao_pmr =
			
			[06_pmr_dias] - [07_pmr_periodo_anterior]
		lineageTag: dc03d6da-4489-4930-ad85-f164872ac32f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 09_valor_aging =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		lineageTag: 2bc60ee4-fc28-4225-aecb-57218f467b29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 11_valor_inadimplente_mes = ```
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    FILTER(
			        ALL(protheus_contasReceber),
			        protheus_contasReceber[data_emissao] <= MAX(calendario[Date]) &&
			        (
			            ISBLANK(protheus_contasReceber[data_baixa]) ||
			            protheus_contasReceber[data_baixa] > MAX(calendario[Date])
			        ) &&
			        protheus_contasReceber[data_vencimento] < MAX(calendario[Date])
			    )
			)
			
			```
		lineageTag: aaa2e6d8-f943-4301-8924-dd7904b156b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 12_total_aberto_mes = ```
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    FILTER(
			        ALL(protheus_contasReceber),
			        protheus_contasReceber[data_emissao] <= MAX(calendario[Date]) &&
			        (
			            ISBLANK(protheus_contasReceber[data_baixa]) ||
			            protheus_contasReceber[data_baixa] > MAX(calendario[Date])
			        )
			    )
			)
			
			```
		lineageTag: b30ec5c9-792c-4dfd-9891-2b4d20e61943

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 13_inadimplencia_percentual_mes = ```
			
			VAR total_mes =
			    [12_total_aberto_mes]
			RETURN
			IF(
			    total_mes > 0,
			    DIVIDE(
			        [11_valor_inadimplente_mes],
			        total_mes
			    ),
			    BLANK()
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 92b7a087-e8f7-4090-ae7c-4f9a520faba4

	measure 20_valor_em_aberto =
			
			CALCULATE(
			    SUM(protheus_contasReceber[saldo]),
			    protheus_contasReceber[saldo] > 0
			)
		lineageTag: fcb96510-1d6d-44f7-a096-d61ccb4a8562

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 21_dias_em_atraso = ```
			
			VAR dias =
			    DATEDIFF(
			        MIN(protheus_contasReceber[data_vencimento]),
			        TODAY(),
			        DAY
			    )
			RETURN
			IF(dias > 0, dias, 0)
			
			```
		formatString: 0
		lineageTag: cf00e4e9-ef1a-4e05-82b7-a8de313b0ae9

	measure 22_status_cliente =
			
			SWITCH(
			    TRUE(),
			    [21_dias_em_atraso] = 0, "Em Dia",
			    [21_dias_em_atraso] <= 30, "Atraso Leve",
			    [21_dias_em_atraso] <= 90, "Atraso Moderado",
			    "Atraso Grave"
			)
		lineageTag: f54af439-07bc-4bb2-94ed-ff45a10b2ab5

	partition medidas_financeiro = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

